// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtzRqMAi6Avhbva6KqFiA7Zwm6LbQ2_Zg',
    appId: '1:239946850735:web:8e29df620f5d3cf950cf5a',
    messagingSenderId: '239946850735',
    projectId: 'easyunilife-9ac67',
    authDomain: 'easyunilife-9ac67.firebaseapp.com',
    databaseURL: 'https://easyunilife-9ac67-default-rtdb.firebaseio.com',
    storageBucket: 'easyunilife-9ac67.appspot.com',
    measurementId: 'G-5XHY1R8CF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2HDELGmMG4ziQIQW02_pLrAvxz7tk0_A',
    appId: '1:239946850735:android:9ce3e2c32212508150cf5a',
    messagingSenderId: '239946850735',
    projectId: 'easyunilife-9ac67',
    databaseURL: 'https://easyunilife-9ac67-default-rtdb.firebaseio.com',
    storageBucket: 'easyunilife-9ac67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF80qyYt6CoVi2m75dicbRkklBb_S-GSE',
    appId: '1:239946850735:ios:efc7732e1142213150cf5a',
    messagingSenderId: '239946850735',
    projectId: 'easyunilife-9ac67',
    databaseURL: 'https://easyunilife-9ac67-default-rtdb.firebaseio.com',
    storageBucket: 'easyunilife-9ac67.appspot.com',
    iosBundleId: 'com.example.appwithapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF80qyYt6CoVi2m75dicbRkklBb_S-GSE',
    appId: '1:239946850735:ios:efc7732e1142213150cf5a',
    messagingSenderId: '239946850735',
    projectId: 'easyunilife-9ac67',
    databaseURL: 'https://easyunilife-9ac67-default-rtdb.firebaseio.com',
    storageBucket: 'easyunilife-9ac67.appspot.com',
    iosBundleId: 'com.example.appwithapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtzRqMAi6Avhbva6KqFiA7Zwm6LbQ2_Zg',
    appId: '1:239946850735:web:9c7aa4ed60c4020c50cf5a',
    messagingSenderId: '239946850735',
    projectId: 'easyunilife-9ac67',
    authDomain: 'easyunilife-9ac67.firebaseapp.com',
    databaseURL: 'https://easyunilife-9ac67-default-rtdb.firebaseio.com',
    storageBucket: 'easyunilife-9ac67.appspot.com',
    measurementId: 'G-5H3QWVS9P9',
  );
}
